### ISSUE TITLE
Error when parsing altitude

### ISSUE THREAD

**Issue by amilbeck** [adriann0/npm-aprs-parser#25]
I was playing around with this package this morning, just trying to capture and parse my own data for a private project I'm working on. Kept running into the `Error when parsing altitude` error found [here](https://github.com/adriann0/npm-aprs-parser/blob/cf5e3a8eeb53a44361b86f270e05444d3ebba6f5/lib/Position/UncompressedPositionParserUtil.js#L65)

I am using APRSDroid and just sending packets from my phone. What I noticed is that the app is sending my altitude over as `/A=-00072`. This doesn't appear to work with the regex match: `altitudeString.match('^[0-9]{6,6}$')`. Seems that it is failing in two places, first being the `-` character. I am on the coast in a flood zone so my location is actually below sea level, and the second is that the matcher here is looking for exactly 6 digits and my altitude only has 5. 

I was able to resolve this by changing the regex to `'^-?[0-9]{5,6}$'` which makes the `-` optional and will accept 5 or 6 digits for the altitude. I'm not sure if this is still accurate but it appears to be working. After changing the regex and running my script again I can now see the Position in the parsed message. 

Do you think this is a valid fix for this problem? Why does the current implementation require a positive altitude of exactly 6 characters? I'll admit, I didn't dive deep enough to see if allowing negative altitudes would cause any other problems in the project. Was just curious if this would be something worth updating?

**Comment by adriann0** [comment]
Thanks for raising this. We are trying to follow [this](http://www.aprs.org/doc/APRS101.PDF) document. It says "Altitude is in format /A=aaaaaa, where aaaaaa is the altitude in feet.". Frankly I just didn't anticipate altitude can be negative therefore this behavior. 

I think it's fine to introduce change you are proposing but I would suggest to enforce there is 6 characters and first one can be minus sign so something like `^[\-0-9][0-9]{5,5}$`.

If you want to prepare PR feel free to submit it. If not let me know and I'll fix it on my own.
