### ISSUE TITLE
Unable to parse location

### ISSUE THREAD

**Issue by klinquist** [adriann0/npm-aprs-parser#3]
I haven't had a chance to troubleshoot this one yet... but aprs.fi parses this location just fine, but npm-aprs-parser does not (doesn't return a data object):

`AF6HO-2>SWRTSY,WIDE2-2,qAR,WA5ZNU-10:'2[^""qj/]"4)}`

It can be found on aprs.fi with the timestamp 2017-02-27 12:15:20 CST
http://aprs.fi/?c=raw&call=AF6HO-2

**Comment by klinquist** [comment]
Found the bug - bottom of page 46 @ http://www.aprs.org/doc/APRS101.PDF

PR incoming :)

**Comment by adriann0** [comment]
Merged :)
