### ISSUE TITLE
Client side usage

### ISSUE THREAD

**Issue by ad1217** [adriann0/npm-aprs-parser#5]
This module seems to work fine on the client side, except that `APRSISConnector.js` requires some nodejs specific modules (`net` and `readline`). Is it possible to only include that file when running on nodejs? I'm currently using Webpack, but would be open to something else if you have another suggestion.

**Comment by adriann0** [comment]
To honest I don't have much experience with this, I created the package for use in nodejs. If you have idea how to fix it I'm open to merging contribution.
